# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LHoY2hLd7lJThlF0ZDbrJyELOMfzT2pQ
"""

# 20보다 작은 값들 중에 7의 배수를 출력하시오.(while 문으로 작성)

n=1
list = []
while n <= 20 :
    if n % 7 == 0 :
        list.append(n)
    n = n + 1
print(list)

# 20보다 작은 값들 중에 7의 배수를 출력하시오.(while 문으로 작성)

n=1
while n <= 20 :
    if n % 7 == 0 :
        print(n)
    n = n + 1